/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import Button from "../components/button/Button";
import Footer from "../components/footer/Footer";
import classes from "../styles/Home.module.css";
// import primaryBtn from "../public/primaryBtn.png";
import SoundWave from "../components/soundwave/SoundWave";
import  {
primaryBtn,

Group79,
Group80,
Group81,
Group83,
Layer2,
Layer3,
speaker,
speaker2,
vector1,
vector2,
vector3,
vector4,
vector5,
vector6,
} from "../public/index"

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Vibin' ape</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.wrapper}>
        <nav className={classes.nav}>
          <Image src="/logo.png" alt="logo" width={147} height={100} />
          <h2>Vibin' Ape</h2>
        </nav>
        <main className={classes.main}>
          <h1 className={classes.title}>Embrace The Vibe</h1>
          <Button
            className={classes.btn}
            image={primaryBtn}
            alt="image title"
          />
        </main>
        <div className={classes.box}>
          <div>
            <Image
              src={Group80}
              alt="image1"
              width={53}
              height={52}
            />
          </div>
          <div>
            <Image
              src={Group79}
              alt="image1"
              width={35}
              height={34}
            />
          </div>
          <div>
            <Image
              src={Group81}
              alt="image1"
              width={71}
              height={71}
            />
          </div>
          <div>
            <Image
              src={Group83}
              alt="image1"
              width={53}
              height={60}
            />
          </div>
          <div>
            <Image
              src={Layer2}
              alt="image1"
              width={64}
              height={59}
            />
          </div>
          <div>
            <Image
              src={speaker}
              alt="image1"
              width={40}
              height={40}
            />
          </div>
          <div>
            <Image
              src={vector2}
              alt="image1"
              width={36}
              height={29}
            />
          </div>
          <div>
            <Image
              src={speaker2}
              alt="image1"
              width={32}
              height={32}
            />
          </div>
          <div>
            <Image
              src={Layer3}
              alt="image1"
              width={28}
              height={30}
            />
          </div>
          <div>
            <Image
              src={vector1}
              alt="image1"
              width={16}
              height={23}
            />
          </div>
          
        </div>
        <SoundWave />
      </div>
    </div>
  );
}
